### ISSUE TITLE
minimize your dependencies as much as possible. 

### ISSUE THREAD

**Issue by omrifima** [mondaycom/node-execution-context#1]
dependencyless code is da best

+ jest should be in devDepndencies. 
+ remove lodash . you dont use it 

https://github.com/mondaycom/node-execution-context/blob/2841d01756f3795a874335ae6931c95ca0ee0c17/package.json#L33

**Comment by shaneer** [comment]
Hey @omrifima - thanks for pointing it out. Fixed!
